### ISSUE TITLE
JedWatson/classnames

### ISSUE THREAD

**Issue by StreetStrider** [lukeed/clsx#1]
https://github.com/JedWatson/classnames

**Comment by lukeed** [comment]
Hi, yes 😆 Not sure what you mean?

**Comment by StreetStrider** [comment]
Nothing, all good.

**Comment by TrySound** [comment]
classnames has a problem with adding esm support
https://github.com/JedWatson/classnames/pull/150

**Comment by jantimon** [comment]
Thanks for the explanation 👍

You should probably add this also to the readme
