### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by maraisr** [lukeed/clsx#3]
First of all love this lib! Neat. :100:

TypeScript people had `@types/classnames` - with this lib being a drop in replacement, should we fork that typings, or simply include it in this repo.

```ts
declare module 'clsx' {
	type ClassValue = string | number | ClassDictionary | ClassArray | undefined | null | boolean;

	interface ClassDictionary {
		[ id: string ]: any;
	}

	interface ClassArray extends Array<ClassValue> {
	}

	type ClassNamesFn = (...classes: ClassValue[]) => string;

	type ClassNamesExport = ClassNamesFn & { default: ClassNamesFn };

	const classNames: ClassNamesExport;

	export = classNames;
}
```
> sourced from: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/classnames/index.d.ts

Not sure if you wan't to include this in your project as a `index.d.ts` in the root.

**Comment by lukeed** [comment]
Hey, thank you~! 🙌 

I'm not really a fan of TypeScript – so my thinking here was that the `@types/classnames` could be used instead (since usage is meant to be identical), ignoring the extra `bind/dedupe` bits, or we could fork it in the DefinitelyTyped repo & publish as its own name.

What do you think?

**Comment by maraisr** [comment]
Yeah sure - we could fork and rename. We just can't use the same lib (@types/classnames), as it binds to a different module.

Would I be right in leaving this for you to handle?

**Comment by lukeed** [comment]
Awesome – did not know that 😆 

It's up to you. Happy to let you take it on over there. If you tag me I'll review & approve! But if you don't want to expend any additional effort, I'll add it to my list.

**Comment by rosskevin** [comment]
@maraisr for reference here is a pull at rifm that I just did to add dtslint and tests.  Should be a similar thing here https://github.com/istarkov/rifm/pull/40
