### ISSUE TITLE
Can you please fix this issue ?

### ISSUE THREAD

**Issue by abdulbasit-94** [lukeed/clsx#41]
import clsx from "clsx";
clsx('text-sm text-bold', 'text-red' , 'text-semibold text-lg', 'text-blue');

This is not going to work fine. only one text- will work when we run this and this will also not override classes.

**Comment by abdulbasit-94** [comment]
This is also for border-  and every other classes have a common prefixes.

**Comment by lukeed** [comment]
I don't know what you're saying is wrong. I just run this as is and it works as expected:

```js
const clsx = require('clsx');
clsx('text-sm text-bold', 'text-red' , 'text-semibold text-lg', 'text-blue');
//=> 'text-sm text-bold text-red text-semibold text-lg text-blue'
```

```js
import clsx from 'clsx';
clsx('text-sm text-bold', 'text-red' , 'text-semibold text-lg', 'text-blue');
//=> 'text-sm text-bold text-red text-semibold text-lg text-blue'
```
