### ISSUE TITLE
Is it possible to enable `sourcemap` ?

### ISSUE THREAD

**Issue by baseplate-admin** [lukeed/clsx#80]
Hi,

Thanks for creating this awesome tool. I was wondering if you could add `sourcemap` for the minified bundles. 

Reasons : 
The original code of `clsx` is not included in the project that uses `clsx`
![image](https://github.com/lukeed/clsx/assets/61817579/3ea2b874-777e-420f-83ea-d9853c1cd3d2)

**Comment by lukeed** [comment]
Much prefer to ship production-ready code especially given that the module is less than 250b. Realistically there's little/no need to actually expand this part of an application. There's lots of `unpkg` & `esm.sh` & `deno.land` usage for this library, so shipping the unminified version will have a measurable impact that I don't feel good about.

**Comment by baseplate-admin** [comment]
Hi, thanks for getting back.

>  so shipping the unminified version

It is not about shipping unminfied version. By enabling source-map, you will just ship a `.map` file, Everything should stay just the same ( plus one `.map` file )
