### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by lokomass** [lukeed/clsx#84]
Hi.
Is it a good practice to use clsx even if I have only one conditionnaly class ?

Exemple

Insteaf of this : 

```
const class = (condition) ? 'Myclass' : undefined
<div className={class}/>
```

I prefer this approach: 

```
<div className={clsx(
{
'Myclass': condition
}
)}/>
```

But in term of performance, is there any impact ?

Thanks for replay

**Comment by ivanabovin** [comment]
One more option - `clsx(condition && 'MyClass')`

**Comment by lukeed** [comment]
Thanks @drwpow; PS 👋 !!
