### ISSUE TITLE
clsx returns only the first element of the array in React Native CLI

### ISSUE THREAD

**Issue by Medkhat** [lukeed/clsx#85]
### Here example:
<img width="662" alt="image" src="https://github.com/lukeed/clsx/assets/42961493/c503adc4-830d-4738-bc06-d07b46854450">

<img width="467" alt="image" src="https://github.com/lukeed/clsx/assets/42961493/b476c259-0d63-4a81-a4e9-cc8d5053e2e8">

### Output
<img width="370" alt="image" src="https://github.com/lukeed/clsx/assets/42961493/18656878-0645-4556-922e-991a25e396db">

**Comment by nishanthbhat07** [comment]
Hey. How did you fix this issue? Facing the same

**Comment by Medkhat** [comment]
@nishanthbhat07 Hi! When you provide a className to the custom component, you need to use a different name instead of "className".

Example: 

`function MyCustomView({ customViewCn }) {
   return <View className={cn("p-3", customViewCn)}>
    {* Children *}
   </View>
}`
