### ISSUE TITLE
clsx/lite accepts ClassDictionary (TypeScript)

### ISSUE THREAD

**Issue by sndrrth** [lukeed/clsx#90]
The TS type of the new `clxs/lite` function includes the `ClassDictionary` type, but why? Dictionaries are not evaluated by this function, so passing them is useless. Wouldn't it be better to exclude it so that TS users are aware of that restriction?

**Comment by lukeed** [comment]
I kept it the same because you should be able to simply modify your bundler's `alias` config to map `clsx` to `clsx/lite` w/o changes or new errors. Also, technically, `clsx/lite` still accepts the non-string input values, it just doesnt do anything with them

**Comment by sndrrth** [comment]
Thanks for the explanation.

> I kept it the same because you should be able to simply modify your bundler's alias config to map clsx to clsx/lite w/o changes or new errors

Wouldn't this be a reason to use a different type? When configuring an alias, you will not get any errors because of the same TS type but the app will just not work anymore, which defeats the purpose of TypeScript.

**Comment by sndrrth** [comment]
Thanks for the explanation.

**Comment by skyrpex** [comment]
> I kept it the same because you should be able to simply modify your bundler's alias config to map clsx to clsx/lite w/o changes or new errors.

That will only hide errors in runtime, no? I don't understand the reasoning 🤔
